# Generated by Django 2.2.11 on 2020-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(default=10, null=True)),
                ('roll_number', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
